// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  activePlayer: __t.identity().name("active_player"),
  phase: __t.string(),
  canEndTurn: __t.bool().name("can_end_turn"),
  inHandTileId: __t.option(__t.u64()).name("in_hand_tile_id"),
  winner: __t.option(__t.identity()),
  lastAction: __t.option(__t.string()).name("last_action"),
});
