// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  ownerId: __t.identity().name("owner_id"),
  color: __t.string(),
  position: __t.u8(),
  isRevealed: __t.bool().name("is_revealed"),
  isInHand: __t.bool().name("is_in_hand"),
  revealedValue: __t.option(__t.u8()).name("revealed_value"),
  jokerSlot: __t.option(__t.u8()).name("joker_slot"),
});
