// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameState = __t.object("GameState", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  activePlayer: __t.identity(),
  phase: __t.string(),
  canEndTurn: __t.bool(),
  inHandTileId: __t.option(__t.u64()),
  winner: __t.option(__t.identity()),
  lastAction: __t.option(__t.string()),
  targetedTileId: __t.option(__t.u64()),
});
export type GameState = __Infer<typeof GameState>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  maxPlayers: __t.u32(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  gameStartsAt: __t.option(__t.u64()),
});
export type Lobby = __Infer<typeof Lobby>;

export const LobbyMember = __t.object("LobbyMember", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  playerIdentity: __t.identity(),
  joinedAt: __t.timestamp(),
  colorPreference: __t.string(),
});
export type LobbyMember = __Infer<typeof LobbyMember>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const TilePool = __t.object("TilePool", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  orderIndex: __t.u8(),
  color: __t.string(),
  value: __t.u8(),
  isDrawn: __t.bool(),
});
export type TilePool = __Infer<typeof TilePool>;

export const TilePublic = __t.object("TilePublic", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  ownerId: __t.identity(),
  color: __t.string(),
  position: __t.u8(),
  isRevealed: __t.bool(),
  isInHand: __t.bool(),
  revealedValue: __t.option(__t.u8()),
  jokerSlot: __t.option(__t.u8()),
});
export type TilePublic = __Infer<typeof TilePublic>;

export const TileSecret = __t.object("TileSecret", {
  id: __t.u64(),
  tilePublicId: __t.u64(),
  ownerId: __t.identity(),
  value: __t.u8(),
});
export type TileSecret = __Infer<typeof TileSecret>;

