// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttackReducer from "../attack_reducer";
import DrawTileReducer from "../draw_tile_reducer";
import EndTurnReducer from "../end_turn_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import SetNameReducer from "../set_name_reducer";

export type AttackParams = __Infer<typeof AttackReducer>;
export type DrawTileParams = __Infer<typeof DrawTileReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;

